substitutions:
  _DESAFIO_K8S_GOLANG_VERSION: "1.0"
steps:
- id: "Build da imagem"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/desafio_k8s_golang:latest', '-t', 'gcr.io/$PROJECT_ID/desafio_k8s_golang:${_DESAFIO_K8S_GOLANG_VERSION}', '.']

- id: "Rodando o teste da função greetings"
  name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-t', '--name', 'desafio_k8s_golang', 'gcr.io/$PROJECT_ID/desafio_k8s_golang:latest', 'go', 'test']


images:
- 'gcr.io/$PROJECT_ID/desafio_k8s_golang:latest'
- 'gcr.io/$PROJECT_ID/desafio_k8s_golang:${_DESAFIO_K8S_GOLANG_VERSION}'
tags: ['cloud-builders-desafio-k8s-golang']