substitutions:
  _DESAFIO_K8S_GOLANG_VERSION: "1.${SHORT_SHA}"
steps:
- id: "Build da imagem"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/desafio_k8s_golang:${_DESAFIO_K8S_GOLANG_VERSION}', '-f', 'Dockerfile.prod', '.']

- id: "Pushing image"
  name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/$PROJECT_ID/desafio_k8s_golang:${_DESAFIO_K8S_GOLANG_VERSION}']

- id: "Adjusting deployment file - k8s"
  name: "gcr.io/cloud-builders/gcloud"
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      sed 's#img-app-deployment#gcr.io/$PROJECT_ID/desafio_k8s_golang:${_DESAFIO_K8S_GOLANG_VERSION}#g' k8s/golang-config.yaml > k8s/golang-new-config.yaml;
      cat k8s/golang-new-config.yaml

- id: "Deploying k8s"
  name: "gcr.io/cloud-builders/kubectl"
  args:
    - 'apply'
    - '-f'
    - 'k8s/golang-new-config.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-fullcycle-laravel'