apiVersion: apps/v1
kind: Deployment
metadata:
    name: golang-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: golang-app
    template:
        metadata:
            labels:
                app: golang-app
        spec:
            containers:
            - name: golang-app
              image: raphaellorencini/desafio_k8s_golang:latest
              ports:
              - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: golang-service
spec:
  type: LoadBalancer
  selector:
    app: golang-app
  ports:
  - port: 8000
    targetPort: 8000